#!/bin/bash
#
# bash completion file for bubblewrap commands
#

_bwrap() {
    local cur prev words cword
    _init_completion || return

	local boolean_options="
		--help
		--unshare-cgroup
		--unshare-cgroup-try
		--unshare-user
		--unshare-user-try
		--unshare-ipc
		--unshare-net
		--unshare-pid
		--unshare-uts
		--version
	"

	local options_with_args="
		$boolean_optons
		--args
		--bind
		--bind-data
		--block-fd
		--chdir
		--dev
		--dev-bind
		--dir
		--exec-label
		--file
		--file-label
		--gid
		--hostname
		--info-fd
		--lock-file
		--proc
		--ro-bind
		--remount-ro
		--seccomp
		--setenv
		--symlink
		--sync-fd
		--uid
		--unsetenv
		--seccomp
		--symlink
		--die-with-parent
	"

	if [[ "$cur" == -* ]]; then
	    COMPREPLY=( $( compgen -W "$boolean_options $options_with_args" -- "$cur" ) )
	fi

	return 0
}
complete -F _bwrap bwrap
